name: "PROD: Build and Deploy to https://program.world"
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: src/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('src/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # test running is integrated into gh-action-master -
      # tests must pass before a deploy will proceed, on master
      - name: All
        run: script/gh-action-master.sh
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
