name: "PROD: Build and Deploy to https://program.world"
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Echo step
        run: echo "::debug Master Build of git-ref ${GITHUB_REF##*/}"

      - name: Checkout Repo
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: src/ts/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('src/ts/package-lock.json') }}

      - uses: actions/cache@v2
        with:
          path: /home/runner/.local/lib/python3.6/site-packages
          key: ${{ runner.os }}-pip-${{ hashFiles('src/py/requirements.txt') }}

      - uses: actions/cache@v2
        with:
          path: /home/runner/.local/bin
          key: ${{ runner.os }}-pybin-${{ hashFiles('src/py/requirements.txt') }}

      # test running is integrated into gh-action-master -
      # tests must pass before a deploy will proceed, on master
      - name: All
        run: script/gh-action-master.sh
        env:
          PW_DEV_UPLOAD_GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.PW_DEV_UPLOAD_GOOGLE_APPLICATION_CREDENTIALS }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
