name: "DEV: Build and Deploy to https://dev-gpk-program-world.web.app"
on:
  push:
    branches-ignore:
      - master

jobs:
  build-and-deploy:
    name: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: src/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('src/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: All
        run: script/gh-action-off-master.sh
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
