name: "DEV: Build and Deploy to https://dev-gpk-program-world.web.app"
on:
  push:
    branches-ignore:
      - master

jobs:
  build-and-deploy:
    name: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: src/ts/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('src/ts/package-lock.json') }}

      - uses: actions/cache@v2
        with:
          path: /home/runner/.local/lib/python3.6/site-packages
          key: ${{ runner.os }}-pip-${{ hashFiles('src/py/requirements.txt') }}

      - uses: actions/cache@v2
        with:
          path: /home/runner/.local/bin
          key: ${{ runner.os }}-pybin-${{ hashFiles('src/py/requirements.txt') }}

      - name: All
        run: script/gh-action-off-master.sh
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      # we run tests and typecheck independently, off-master,
      # because these things are not prerequisites for dev deployment.
      - name: Typescript Tests
        run: script/test_ts.sh

      - name: Python Tests
        run: script/test_py.sh

      - name: Python Typecheck
        run: script/typecheck_py.sh
